pages:
  image: node:8-jessie
  stage: deploy
  script:
  - yarn install
  - yarn build
  - yarn export
  - cp -r public out/
  - mv public tmp
  - mv out public
  artifacts:
    paths:
    - public
  only:
  - master